# Generated by Django 4.0.2 on 2022-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notverfahren_medizin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagesaufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_task_day', models.CharField(max_length=100)),
                ('flight_task_night', models.CharField(max_length=100)),
                ('med_task_day', models.CharField(max_length=100)),
                ('med_task_night', models.CharField(max_length=100)),
            ],
        ),
    ]
