# Generated by Django 4.0.2 on 2022-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tagesaufgabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesaufgabe',
            name='tag',
            field=models.CharField(default='Montag', max_length=50),
        ),
    ]
