# Generated by Django 4.0.2 on 2022-03-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_notverfahren_medizin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notverfahren_flug',
            options={'verbose_name_plural': 'Notverfahren_Flug'},
        ),
    ]
